image: fedora

build:
  tags: 
    - build
  stage: build
  before_script:
      # step 1: install dynamically linked libraries that are required by the static dependencies:
      - dnf -y install glibc-devel gcc-c++ gmp-devel automake autoconf autoconf-archive
      # step 2: install statically linked libraries
      - dnf -y install boost-static mpfi-static
      # step 3: install static dependencies that don't have a DNF package
      - curl https://libntl.org/ntl-11.5.1.tar.gz --output ntl.tar.gz
      - gunzip ntl.tar.gz
      - tar xf ntl.tar
      - cd ntl-11.5.1/src
      - ./configure
      - make
      - make install
      - source ci_before_build.sh
      - cd ../..
  script:
    - autoreconf -vi
    - cd build
    - sh ../configure "CXXFLAGS=$CXXFLAGS -fdiagnostics-color" --without-mpfr 
    - make
  artifacts:
    paths:
      - build/test
      - build/main
    expire_in: 1 day

# run tests using the binary built before
test:
  tags: 
    - test
  stage: test 
  script:
    - ./build/test -r junit -o build/report.xml
  artifacts:
    paths:
      - build/report.xml
    when: always
    reports:
      junit: build/report.xml
    expire_in: 1 month

