#
# File:  appl/Arithmetic/Makefile.dir
# Author: Reginald Lybbert (2016-07-19)
# Version: $Id$
#
# This is only a partial makefile, included by the root makefile.
# It contains build rules only for files in this directory.
# All paths must be relative to the location of the root makefile.
#

# Register sources with the root makefile.
APPL_SRC += appl/Tests/Arithmetic/QQ_ZZ_Tests.cpp
APPL_SRC += appl/Tests/Arithmetic/QQ_ZZpX_Tests.cpp
APPL_SRC += appl/Tests/Arithmetic/QQ_ZZpEX_Tests.cpp
APPL_SRC += appl/Tests/Arithmetic/QQ_zzpX_Tests.cpp
APPL_SRC += appl/Tests/Arithmetic/QQ_zzpEX_Tests.cpp
APPL_SRC += appl/Tests/Arithmetic/QQ_GF2EX_Tests.cpp
APPL_SRC += appl/Tests/Arithmetic/QQ_long_Tests.cpp  

